version: '3'

services:

  mongo:
    image: mongo:3.2
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo_data:/data/db
    ports:
        - "127.0.0.1:27017:27017"

  web:
    build: .
    command: python app/app.py
    volumes:
      - .:/dungeon_brawl
    ports:
      - "0.0.0.0:5000:5000"
    depends_on:
      - mongo
